version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: EventClean
    restart: always
    environment:
      POSTGRES_DB: EventClean
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"